function bus = init_bus()
%INIT_BUS Create empty message queues for all simulated channels.
bus = struct( ...
    'CAN1', {{}}, ...
    'CAN2', {{}}, ...
    'CAN3', {{}}, ...
    'Eth1', {{}}, ...
    'Eth2', {{}}, ...
    'Eth3', {{}}, ...
    'Eth4', {{}});
end
